FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install dbt-core dbt-sqlite

COPY backend/       backend/
COPY fp_growth_mba/ fp_growth_mba/
COPY docker/profiles.yml /root/.dbt/profiles.yml

COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
